### ISSUE TITLE
Cleaner import line

### ISSUE THREAD

**Issue by dessalines** [rileynull/RedditLemmyImporter#5]
Instead of this:

`Originally posted on r/GenZhou by u/Lenins2ndCat (score +10)`

This would be clearer IMO:

`u/Lenins2ndCat to r/GenZhou`

No score necessary, since those are getting transferred correctly.

**Comment by mesmere** [comment]
I was going to go with

`[username] (score) - Originally posted on r/GenZhou`

as she suggested. My thinking on the score was to more visibly preserve the original reddit score, since people can continue voting on it. But yeah that's probably just confusing. I suppose I'll remove the score.

I'll close this issue when I push the new format. Fighting with lemmy at the moment cause it doesn't want to start up anymore 😕 (edit: figured it out, it's just LemmyNet/lemmy/issues/1477 lol)

**Comment by dessalines** [comment]
No probs. Once you get a new version, let me know and I can forward that info to the lemmygrad ppl to do another import to replace the old archive.

**Comment by mesmere** [comment]
This is done, check out the new screenshots in the readme.
